### PR TITLE
Add curl_command input so that it can be parsed and use in the PHP request

### PR DESCRIPTION
**Pull request by kadogo**
Hello

The cookie need to match if the stories are private. The easiest way that I find to use them was to just use a "copy as curl" for the main page of Facebook and parse it directly.

If you find a better way, don't hesitate to tell me or modify directly the code ^^

Cheers

### CODE REVIEW

**Comment by vikas5914** [comment]
@kadogo Thanks for the PR; however, I will not merge this. This was designed for only public videos. Also, asking for someone's cookies is a security risk. You should not provide your cookies to a random website.

**Comment by kadogo** [comment]
Hello @vikas5914 

That's true, I didn't think about having the service shared but only used with it's self-hosted because I don't think, or I didn't notice that there is an easy way to download the videos for now.

**Comment by vikas5914** [comment]
@kadogo For self-hosted, you can add your cookies to the the PHP file.

**Comment by kadogo** [comment]
Hello @vikas5914 It's true that if the cookie have no expiration time that will be better.

It's maybe even better to have a configuration file.
It will less lead to a security issue, it could be used with personal cookie if self-hosted and there will be no need to catch the cookie again.

If that sound good for you, I will surely open this PR again if I can make it working.

**Comment by vikas5914** [comment]
@kadogo creates an empty file called `cookies.txt` in the `app` folder and reads the content. If people want to put their cookies in that, they can.

**Pull request closed without merging**
